numservers: 3
numfailures: 1
servers:
  - id: 0
    ip: 127.0.0.1
    port: 3000
    alive: false
  - id: 1
    ip: 127.0.0.1
    port: 3001
    alive: false
  - id: 2
    ip: 127.0.0.1
    port: 3002
    alive: false